## Get Request For Users Controller
POST http://localhost:3030/users
Content-Type: application/json

{
    "firstName": "Eduardo",
    "lastName": "Doe",
    "email": "edu@doe22.com",
    "password": "password@123"
}

POST http://localhost:3030/users/create-many
Content-Type: application/json

{
    "users": [
        {
            "firstName": "Mark",
            "lastName": "Does",
            "email": "markk@doebosg.com",
            "password": "password@123"
        },
        {
            "firstName": "Joanne",
            "lastName": "Doesnt",
            "email": "john@doe25gta.com",
            "password": "password@123"
        }
    ]
}